# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 21ef64489fc3a79e2f7c41ab4da1d67894a53f234c30a43d8a387a8cb860df838946dad2aeedddda31b977d97f45bf8e30eef3ae7739df94a16b64afafc0d419

test:
  secret_key_base: d5ad303e12cb39aeef1b98f7b7f0472c38c35d2250e3b27556bcf6a7f7549268bd4d82f5d9fba6d71344b289c3dedf9a892c2b4030f66c0c126a6447730924a1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
